language: python
python:
  - "3.6-dev"
  - "3.5"
  - "3.4"
  - "2.7"
matrix:
  allow_failures:
    - python: "3.6-dev"
before_install:
- pip install git+git://git.srobo.org/comp/ranker.git
- pip install --upgrade setuptools
install: python setup.py install
script:
- ./run-tests
# Deliberately after running the real tests so that we can't accidentally
# depend on it
- pip install pylint
- ./lint
