language: python
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"
  - "3.4"
matrix:
  allow_failures:
    - python: "3.7-dev"
before_install:
  - pip install git+https://github.com/PeterJCLaw/ranker.git@python3-only
install: pip install .
script:
- ./run-tests
# Deliberately after running the real tests so that we can't accidentally
# depend on it
- pip install pylint
- ./lint
